apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: istio-system

data:
  config.yaml: |
    domain: istio-ratelimit
    descriptors:
      - key: acf-x-user-email
        rate_limit:
          unit: minute
          requests_per_unit: 60
